package de.rwth.swc.qrs2019;

import de.rwth.swc.coffee4j.model.Parameter;
import de.rwth.swc.qrs2019.modelling.Config3;
import de.rwth.swc.qrs2019.modelling.Scenario;
import de.rwth.swc.qrs2019.modelling.Value7;

public class Scenario1_4 implements Scenario {

    public int[] getParameterOrder(int index) {
        return PARAMETER_ORDER[index];
    }

    public Parameter[] getOrderedParameters(int index) {
        return ORDERED_PARAMETERS[index];
    }

    public int[][] PARAMETER_ORDER = {
            new int[]{ 4, 3, 6, 1, 10, 19, 0, 13, 7, 14, 16, 17, 11, 15, 18, 12, 2, 8, 5, 9 },
            new int[]{ 6, 14, 17, 12, 4, 0, 1, 9, 18, 13, 10, 16, 2, 15, 3, 5, 7, 19, 8, 11 },
            new int[]{ 9, 4, 7, 8, 11, 15, 0, 10, 6, 12, 18, 16, 17, 13, 14, 3, 5, 19, 2, 1 },
            new int[]{ 1, 17, 2, 5, 9, 0, 14, 11, 12, 18, 6, 15, 16, 4, 3, 10, 19, 13, 8, 7 },
            new int[]{ 11, 15, 14, 4, 0, 8, 10, 1, 3, 9, 5, 13, 17, 18, 7, 2, 19, 6, 12, 16 },
            new int[]{ 12, 1, 11, 14, 7, 18, 15, 16, 13, 3, 5, 17, 4, 10, 2, 8, 6, 0, 9, 19 },
            new int[]{ 11, 5, 19, 9, 6, 1, 17, 12, 0, 15, 14, 8, 2, 7, 16, 13, 18, 4, 10, 3 },
            new int[]{ 4, 7, 14, 1, 8, 15, 16, 3, 11, 17, 2, 10, 19, 0, 9, 13, 18, 5, 6, 12 },
            new int[]{ 10, 8, 18, 0, 16, 3, 2, 6, 1, 15, 4, 17, 13, 14, 7, 5, 12, 11, 9, 19 },
            new int[]{ 13, 4, 10, 16, 3, 7, 14, 17, 18, 8, 2, 15, 0, 6, 5, 12, 19, 9, 11, 1 },
    };

    public static final Parameter[][] ORDERED_PARAMETERS = {
            new Parameter[] {Parameter.parameter("v5").values(Value7.I, Value7.IV, Value7.VI, Value7.II, Value7.III, Value7.VII, Value7.V).build(),
                    Parameter.parameter("v4").values(Value7.VI, Value7.II, Value7.I, Value7.VII, Value7.III, Value7.IV, Value7.V).build(),
                    Parameter.parameter("v7").values(Value7.II, Value7.I, Value7.V, Value7.VI, Value7.VII, Value7.IV, Value7.III).build(),
                    Parameter.parameter("v2").values(Value7.II, Value7.IV, Value7.I, Value7.V, Value7.VI, Value7.III, Value7.VII).build(),
                    Parameter.parameter("x1").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x10").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v1").values(Value7.VI, Value7.IV, Value7.I, Value7.VII, Value7.II, Value7.V, Value7.III).build(),
                    Parameter.parameter("x4").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v8").values(Value7.III, Value7.VI, Value7.VII, Value7.IV, Value7.V, Value7.II, Value7.I).build(),
                    Parameter.parameter("x5").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x7").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x8").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x2").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x6").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x9").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x3").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v3").values(Value7.IV, Value7.VII, Value7.I, Value7.II, Value7.III, Value7.V, Value7.VI).build(),
                    Parameter.parameter("v9").values(Value7.V, Value7.IV, Value7.III, Value7.VII, Value7.II, Value7.VI, Value7.I).build(),
                    Parameter.parameter("v6").values(Value7.IV, Value7.VII, Value7.III, Value7.V, Value7.II, Value7.I, Value7.VI).build(),
                    Parameter.parameter("v10").values(Value7.II, Value7.VII, Value7.IV, Value7.I, Value7.VI, Value7.V, Value7.III).build()},

            new Parameter[] {Parameter.parameter("v7").values(Value7.III, Value7.I, Value7.VI, Value7.V, Value7.IV, Value7.II, Value7.VII).build(),
                    Parameter.parameter("x5").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x8").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x3").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v5").values(Value7.IV, Value7.VII, Value7.VI, Value7.V, Value7.II, Value7.I, Value7.III).build(),
                    Parameter.parameter("v1").values(Value7.V, Value7.IV, Value7.VI, Value7.I, Value7.VII, Value7.III, Value7.II).build(),
                    Parameter.parameter("v2").values(Value7.VII, Value7.III, Value7.V, Value7.I, Value7.IV, Value7.II, Value7.VI).build(),
                    Parameter.parameter("v10").values(Value7.V, Value7.VII, Value7.IV, Value7.II, Value7.VI, Value7.I, Value7.III).build(),
                    Parameter.parameter("x9").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x4").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x1").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x7").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v3").values(Value7.V, Value7.VII, Value7.II, Value7.VI, Value7.III, Value7.IV, Value7.I).build(),
                    Parameter.parameter("x6").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v4").values(Value7.IV, Value7.I, Value7.V, Value7.VII, Value7.II, Value7.VI, Value7.III).build(),
                    Parameter.parameter("v6").values(Value7.VII, Value7.III, Value7.V, Value7.I, Value7.II, Value7.VI, Value7.IV).build(),
                    Parameter.parameter("v8").values(Value7.VII, Value7.VI, Value7.II, Value7.I, Value7.III, Value7.V, Value7.IV).build(),
                    Parameter.parameter("x10").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v9").values(Value7.I, Value7.IV, Value7.VII, Value7.VI, Value7.II, Value7.III, Value7.V).build(),
                    Parameter.parameter("x2").values(Config3.B, Config3.C, Config3.A).build()},

            new Parameter[] {Parameter.parameter("v10").values(Value7.II, Value7.IV, Value7.I, Value7.V, Value7.VII, Value7.III, Value7.VI).build(),
                    Parameter.parameter("v5").values(Value7.I, Value7.III, Value7.II, Value7.V, Value7.VII, Value7.VI, Value7.IV).build(),
                    Parameter.parameter("v8").values(Value7.IV, Value7.VI, Value7.VII, Value7.V, Value7.I, Value7.III, Value7.II).build(),
                    Parameter.parameter("v9").values(Value7.VII, Value7.III, Value7.II, Value7.IV, Value7.V, Value7.I, Value7.VI).build(),
                    Parameter.parameter("x2").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x6").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v1").values(Value7.III, Value7.VII, Value7.II, Value7.VI, Value7.IV, Value7.I, Value7.V).build(),
                    Parameter.parameter("x1").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v7").values(Value7.VII, Value7.I, Value7.III, Value7.V, Value7.II, Value7.IV, Value7.VI).build(),
                    Parameter.parameter("x3").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x9").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x7").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x8").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("x4").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x5").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v4").values(Value7.IV, Value7.VI, Value7.II, Value7.III, Value7.I, Value7.VII, Value7.V).build(),
                    Parameter.parameter("v6").values(Value7.VI, Value7.II, Value7.IV, Value7.I, Value7.III, Value7.V, Value7.VII).build(),
                    Parameter.parameter("x10").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v3").values(Value7.VII, Value7.V, Value7.II, Value7.I, Value7.IV, Value7.VI, Value7.III).build(),
                    Parameter.parameter("v2").values(Value7.III, Value7.II, Value7.VII, Value7.I, Value7.V, Value7.IV, Value7.VI).build()},

            new Parameter[] {Parameter.parameter("v2").values(Value7.IV, Value7.VII, Value7.III, Value7.II, Value7.VI, Value7.V, Value7.I).build(),
                    Parameter.parameter("x8").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v3").values(Value7.III, Value7.VI, Value7.IV, Value7.VII, Value7.V, Value7.II, Value7.I).build(),
                    Parameter.parameter("v6").values(Value7.V, Value7.VII, Value7.III, Value7.I, Value7.II, Value7.IV, Value7.VI).build(),
                    Parameter.parameter("v10").values(Value7.III, Value7.IV, Value7.V, Value7.VI, Value7.II, Value7.VII, Value7.I).build(),
                    Parameter.parameter("v1").values(Value7.V, Value7.II, Value7.III, Value7.IV, Value7.I, Value7.VII, Value7.VI).build(),
                    Parameter.parameter("x5").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("x2").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x3").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x9").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v7").values(Value7.II, Value7.IV, Value7.VI, Value7.I, Value7.VII, Value7.III, Value7.V).build(),
                    Parameter.parameter("x6").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x7").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v5").values(Value7.VII, Value7.IV, Value7.III, Value7.I, Value7.VI, Value7.V, Value7.II).build(),
                    Parameter.parameter("v4").values(Value7.I, Value7.III, Value7.VII, Value7.VI, Value7.IV, Value7.V, Value7.II).build(),
                    Parameter.parameter("x1").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x10").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x4").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v9").values(Value7.VII, Value7.I, Value7.V, Value7.IV, Value7.III, Value7.II, Value7.VI).build(),
                    Parameter.parameter("v8").values(Value7.II, Value7.V, Value7.VI, Value7.I, Value7.IV, Value7.III, Value7.VII).build()},

            new Parameter[] {Parameter.parameter("x2").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x6").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("x5").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v5").values(Value7.VII, Value7.V, Value7.I, Value7.VI, Value7.II, Value7.IV, Value7.III).build(),
                    Parameter.parameter("v1").values(Value7.II, Value7.IV, Value7.III, Value7.VI, Value7.I, Value7.VII, Value7.V).build(),
                    Parameter.parameter("v9").values(Value7.VII, Value7.I, Value7.V, Value7.VI, Value7.IV, Value7.III, Value7.II).build(),
                    Parameter.parameter("x1").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v2").values(Value7.VI, Value7.IV, Value7.III, Value7.V, Value7.VII, Value7.I, Value7.II).build(),
                    Parameter.parameter("v4").values(Value7.VII, Value7.VI, Value7.III, Value7.II, Value7.V, Value7.IV, Value7.I).build(),
                    Parameter.parameter("v10").values(Value7.V, Value7.VI, Value7.IV, Value7.III, Value7.I, Value7.VII, Value7.II).build(),
                    Parameter.parameter("v6").values(Value7.VII, Value7.I, Value7.IV, Value7.II, Value7.VI, Value7.III, Value7.V).build(),
                    Parameter.parameter("x4").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x8").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("x9").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v8").values(Value7.VI, Value7.II, Value7.V, Value7.IV, Value7.I, Value7.VII, Value7.III).build(),
                    Parameter.parameter("v3").values(Value7.VI, Value7.III, Value7.VII, Value7.IV, Value7.II, Value7.I, Value7.V).build(),
                    Parameter.parameter("x10").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v7").values(Value7.V, Value7.VII, Value7.I, Value7.IV, Value7.III, Value7.II, Value7.VI).build(),
                    Parameter.parameter("x3").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x7").values(Config3.B, Config3.A, Config3.C).build()},

            new Parameter[] {Parameter.parameter("x3").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v2").values(Value7.II, Value7.V, Value7.IV, Value7.VII, Value7.I, Value7.VI, Value7.III).build(),
                    Parameter.parameter("x2").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x5").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v8").values(Value7.IV, Value7.III, Value7.I, Value7.VI, Value7.VII, Value7.V, Value7.II).build(),
                    Parameter.parameter("x9").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("x6").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x7").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x4").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v4").values(Value7.VI, Value7.III, Value7.V, Value7.VII, Value7.II, Value7.I, Value7.IV).build(),
                    Parameter.parameter("v6").values(Value7.V, Value7.I, Value7.VII, Value7.IV, Value7.VI, Value7.II, Value7.III).build(),
                    Parameter.parameter("x8").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v5").values(Value7.VII, Value7.IV, Value7.V, Value7.III, Value7.II, Value7.I, Value7.VI).build(),
                    Parameter.parameter("x1").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v3").values(Value7.II, Value7.III, Value7.VII, Value7.V, Value7.VI, Value7.IV, Value7.I).build(),
                    Parameter.parameter("v9").values(Value7.I, Value7.VI, Value7.VII, Value7.III, Value7.V, Value7.II, Value7.IV).build(),
                    Parameter.parameter("v7").values(Value7.II, Value7.V, Value7.VI, Value7.VII, Value7.IV, Value7.I, Value7.III).build(),
                    Parameter.parameter("v1").values(Value7.V, Value7.I, Value7.II, Value7.IV, Value7.III, Value7.VI, Value7.VII).build(),
                    Parameter.parameter("v10").values(Value7.V, Value7.III, Value7.I, Value7.II, Value7.IV, Value7.VII, Value7.VI).build(),
                    Parameter.parameter("x10").values(Config3.C, Config3.A, Config3.B).build()},

            new Parameter[] {Parameter.parameter("x2").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("v6").values(Value7.VII, Value7.I, Value7.II, Value7.V, Value7.IV, Value7.III, Value7.VI).build(),
                    Parameter.parameter("x10").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v10").values(Value7.II, Value7.VII, Value7.IV, Value7.I, Value7.III, Value7.V, Value7.VI).build(),
                    Parameter.parameter("v7").values(Value7.III, Value7.V, Value7.II, Value7.VI, Value7.VII, Value7.IV, Value7.I).build(),
                    Parameter.parameter("v2").values(Value7.V, Value7.I, Value7.III, Value7.VII, Value7.IV, Value7.II, Value7.VI).build(),
                    Parameter.parameter("x8").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x3").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v1").values(Value7.VI, Value7.II, Value7.I, Value7.IV, Value7.V, Value7.III, Value7.VII).build(),
                    Parameter.parameter("x6").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x5").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v9").values(Value7.III, Value7.VII, Value7.II, Value7.VI, Value7.IV, Value7.I, Value7.V).build(),
                    Parameter.parameter("v3").values(Value7.V, Value7.VI, Value7.II, Value7.VII, Value7.IV, Value7.I, Value7.III).build(),
                    Parameter.parameter("v8").values(Value7.III, Value7.VI, Value7.IV, Value7.V, Value7.II, Value7.I, Value7.VII).build(),
                    Parameter.parameter("x7").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x4").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x9").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v5").values(Value7.VII, Value7.I, Value7.V, Value7.IV, Value7.II, Value7.VI, Value7.III).build(),
                    Parameter.parameter("x1").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v4").values(Value7.V, Value7.I, Value7.IV, Value7.III, Value7.II, Value7.VII, Value7.VI).build()},

            new Parameter[] {Parameter.parameter("v5").values(Value7.III, Value7.IV, Value7.I, Value7.VI, Value7.V, Value7.VII, Value7.II).build(),
                    Parameter.parameter("v8").values(Value7.II, Value7.VII, Value7.I, Value7.III, Value7.VI, Value7.IV, Value7.V).build(),
                    Parameter.parameter("x5").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v2").values(Value7.II, Value7.I, Value7.V, Value7.VII, Value7.VI, Value7.III, Value7.IV).build(),
                    Parameter.parameter("v9").values(Value7.VI, Value7.II, Value7.V, Value7.VII, Value7.III, Value7.IV, Value7.I).build(),
                    Parameter.parameter("x6").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("x7").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v4").values(Value7.VII, Value7.IV, Value7.I, Value7.III, Value7.V, Value7.VI, Value7.II).build(),
                    Parameter.parameter("x2").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x8").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("v3").values(Value7.VI, Value7.VII, Value7.V, Value7.II, Value7.III, Value7.IV, Value7.I).build(),
                    Parameter.parameter("x1").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x10").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v1").values(Value7.I, Value7.IV, Value7.V, Value7.VII, Value7.VI, Value7.II, Value7.III).build(),
                    Parameter.parameter("v10").values(Value7.III, Value7.II, Value7.VII, Value7.V, Value7.VI, Value7.IV, Value7.I).build(),
                    Parameter.parameter("x4").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("x9").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("v6").values(Value7.I, Value7.VII, Value7.III, Value7.II, Value7.V, Value7.VI, Value7.IV).build(),
                    Parameter.parameter("v7").values(Value7.II, Value7.VII, Value7.V, Value7.I, Value7.IV, Value7.VI, Value7.III).build(),
                    Parameter.parameter("x3").values(Config3.C, Config3.B, Config3.A).build()},

            new Parameter[] {Parameter.parameter("x1").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("v9").values(Value7.VI, Value7.V, Value7.I, Value7.III, Value7.IV, Value7.II, Value7.VII).build(),
                    Parameter.parameter("x9").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v1").values(Value7.II, Value7.III, Value7.V, Value7.VII, Value7.I, Value7.VI, Value7.IV).build(),
                    Parameter.parameter("x7").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("v4").values(Value7.VI, Value7.V, Value7.I, Value7.VII, Value7.IV, Value7.II, Value7.III).build(),
                    Parameter.parameter("v3").values(Value7.I, Value7.VI, Value7.III, Value7.V, Value7.VII, Value7.II, Value7.IV).build(),
                    Parameter.parameter("v7").values(Value7.VII, Value7.III, Value7.I, Value7.II, Value7.IV, Value7.VI, Value7.V).build(),
                    Parameter.parameter("v2").values(Value7.V, Value7.I, Value7.VI, Value7.II, Value7.IV, Value7.VII, Value7.III).build(),
                    Parameter.parameter("x6").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("v5").values(Value7.IV, Value7.VI, Value7.II, Value7.V, Value7.VII, Value7.I, Value7.III).build(),
                    Parameter.parameter("x8").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x4").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("x5").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v8").values(Value7.VI, Value7.VII, Value7.I, Value7.III, Value7.IV, Value7.V, Value7.II).build(),
                    Parameter.parameter("v6").values(Value7.VI, Value7.I, Value7.III, Value7.V, Value7.II, Value7.VII, Value7.IV).build(),
                    Parameter.parameter("x3").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("x2").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v10").values(Value7.VII, Value7.V, Value7.I, Value7.III, Value7.II, Value7.IV, Value7.VI).build(),
                    Parameter.parameter("x10").values(Config3.C, Config3.A, Config3.B).build()},

            new Parameter[] {Parameter.parameter("x4").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v5").values(Value7.VI, Value7.II, Value7.VII, Value7.V, Value7.I, Value7.III, Value7.IV).build(),
                    Parameter.parameter("x1").values(Config3.A, Config3.C, Config3.B).build(),
                    Parameter.parameter("x7").values(Config3.C, Config3.B, Config3.A).build(),
                    Parameter.parameter("v4").values(Value7.II, Value7.VI, Value7.I, Value7.V, Value7.III, Value7.VII, Value7.IV).build(),
                    Parameter.parameter("v8").values(Value7.II, Value7.VI, Value7.VII, Value7.V, Value7.IV, Value7.III, Value7.I).build(),
                    Parameter.parameter("x5").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("x8").values(Config3.C, Config3.A, Config3.B).build(),
                    Parameter.parameter("x9").values(Config3.B, Config3.C, Config3.A).build(),
                    Parameter.parameter("v9").values(Value7.V, Value7.IV, Value7.VI, Value7.I, Value7.II, Value7.III, Value7.VII).build(),
                    Parameter.parameter("v3").values(Value7.III, Value7.VI, Value7.V, Value7.IV, Value7.I, Value7.II, Value7.VII).build(),
                    Parameter.parameter("x6").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v1").values(Value7.IV, Value7.I, Value7.V, Value7.III, Value7.VII, Value7.II, Value7.VI).build(),
                    Parameter.parameter("v7").values(Value7.II, Value7.VI, Value7.VII, Value7.V, Value7.IV, Value7.III, Value7.I).build(),
                    Parameter.parameter("v6").values(Value7.VI, Value7.IV, Value7.I, Value7.III, Value7.V, Value7.VII, Value7.II).build(),
                    Parameter.parameter("x3").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("x10").values(Config3.A, Config3.B, Config3.C).build(),
                    Parameter.parameter("v10").values(Value7.III, Value7.II, Value7.VI, Value7.VII, Value7.IV, Value7.I, Value7.V).build(),
                    Parameter.parameter("x2").values(Config3.B, Config3.A, Config3.C).build(),
                    Parameter.parameter("v2").values(Value7.I, Value7.IV, Value7.VI, Value7.V, Value7.II, Value7.III, Value7.VII).build()}

    };
}
