package de.rwth.swc.qrs2019;

import de.rwth.swc.coffee4j.model.Parameter;
import de.rwth.swc.qrs2019.modelling.Config2;
import de.rwth.swc.qrs2019.modelling.Scenario;
import de.rwth.swc.qrs2019.modelling.Value5;

public class Scenario1_3 implements Scenario {

    public int[] getParameterOrder(int index) {
        return PARAMETER_ORDER[index];
    }

    public Parameter[] getOrderedParameters(int index) {
        return ORDERED_PARAMETERS[index];
    }

    public int[][] PARAMETER_ORDER = {
            new int[]{ 4, 16, 12, 6, 3, 11, 0, 15, 2, 17, 8, 18, 5, 14, 10, 19, 9, 7, 13, 1 },
            new int[]{ 19, 6, 0, 7, 18, 16, 12, 3, 2, 4, 13, 17, 1, 14, 5, 8, 11, 10, 15, 9 },
            new int[]{ 11, 19, 7, 12, 6, 13, 3, 4, 18, 5, 17, 8, 16, 14, 9, 1, 10, 2, 0, 15 },
            new int[]{ 11, 17, 10, 9, 6, 18, 3, 1, 5, 14, 4, 7, 15, 19, 12, 8, 16, 0, 13, 2 },
            new int[]{ 18, 4, 3, 16, 6, 11, 12, 5, 14, 8, 9, 13, 2, 1, 15, 19, 17, 7, 0, 10 },
            new int[]{ 9, 4, 12, 18, 10, 5, 2, 19, 1, 15, 14, 13, 7, 17, 8, 0, 11, 16, 6, 3 },
            new int[]{ 18, 19, 5, 9, 7, 14, 4, 3, 16, 1, 8, 6, 11, 0, 10, 2, 12, 15, 17, 13 },
            new int[]{ 18, 10, 9, 8, 5, 12, 19, 3, 4, 2, 6, 14, 0, 15, 17, 11, 16, 1, 7, 13 },
            new int[]{ 18, 15, 2, 10, 16, 3, 9, 5, 13, 14, 19, 11, 12, 1, 17, 4, 6, 0, 8, 7 },
            new int[]{ 5, 3, 19, 14, 6, 10, 1, 18, 9, 2, 8, 12, 4, 13, 11, 7, 17, 16, 15, 0 },

    };

    public static final Parameter[][] ORDERED_PARAMETERS = {
            new Parameter[] {
                    Parameter.parameter("v5").values(Value5.II, Value5.V, Value5.I, Value5.III, Value5.IV).build(),
                    Parameter.parameter("x7").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v7").values(Value5.IV, Value5.V, Value5.II, Value5.III, Value5.I).build(),
                    Parameter.parameter("v4").values(Value5.I, Value5.II, Value5.IV, Value5.III, Value5.V).build(),
                    Parameter.parameter("x2").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v1").values(Value5.I, Value5.IV, Value5.III, Value5.II, Value5.V).build(),
                    Parameter.parameter("x6").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v3").values(Value5.IV, Value5.III, Value5.II, Value5.V, Value5.I).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v9").values(Value5.II, Value5.III, Value5.V, Value5.IV, Value5.I).build(),
                    Parameter.parameter("x9").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v6").values(Value5.V, Value5.III, Value5.II, Value5.I, Value5.IV).build(),
                    Parameter.parameter("x5").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x1").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x10").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v10").values(Value5.III, Value5.IV, Value5.II, Value5.I, Value5.V).build(),
                    Parameter.parameter("v8").values(Value5.II, Value5.III, Value5.I, Value5.V, Value5.IV).build(),
                    Parameter.parameter("x4").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v2").values(Value5.III, Value5.II, Value5.I, Value5.IV, Value5.V).build()
            },
            new Parameter[] {
                    Parameter.parameter("x10").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v7").values(Value5.I, Value5.II, Value5.III, Value5.IV, Value5.V).build(),
                    Parameter.parameter("v1").values(Value5.II, Value5.V, Value5.I, Value5.III, Value5.IV).build(),
                    Parameter.parameter("v8").values(Value5.III, Value5.V, Value5.I, Value5.II, Value5.IV).build(),
                    Parameter.parameter("x9").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x7").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x3").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v4").values(Value5.II, Value5.I, Value5.V, Value5.IV, Value5.III).build(),
                    Parameter.parameter("v3").values(Value5.V, Value5.II, Value5.III, Value5.I, Value5.IV).build(),
                    Parameter.parameter("v5").values(Value5.IV, Value5.III, Value5.I, Value5.V, Value5.II).build(),
                    Parameter.parameter("x4").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v2").values(Value5.V, Value5.I, Value5.IV, Value5.II, Value5.III).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v6").values(Value5.I, Value5.V, Value5.II, Value5.III, Value5.IV).build(),
                    Parameter.parameter("v9").values(Value5.III, Value5.IV, Value5.V, Value5.I, Value5.II).build(),
                    Parameter.parameter("x2").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x1").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x6").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v10").values(Value5.II, Value5.I, Value5.V, Value5.IV, Value5.III).build()
            },
            new Parameter[] {
                    Parameter.parameter("x2").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x10").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v8").values(Value5.III, Value5.I, Value5.V, Value5.II, Value5.IV).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v7").values(Value5.IV, Value5.I, Value5.III, Value5.V, Value5.II).build(),
                    Parameter.parameter("x4").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v4").values(Value5.IV, Value5.I, Value5.III, Value5.V, Value5.II).build(),
                    Parameter.parameter("v5").values(Value5.II, Value5.III, Value5.IV, Value5.I, Value5.V).build(),
                    Parameter.parameter("x9").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v6").values(Value5.II, Value5.I, Value5.V, Value5.IV, Value5.III).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v9").values(Value5.I, Value5.IV, Value5.II, Value5.III, Value5.V).build(),
                    Parameter.parameter("x7").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x5").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v10").values(Value5.IV, Value5.II, Value5.V, Value5.I, Value5.III).build(),
                    Parameter.parameter("v2").values(Value5.II, Value5.III, Value5.IV, Value5.I, Value5.V).build(),
                    Parameter.parameter("x1").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v3").values(Value5.II, Value5.III, Value5.IV, Value5.V, Value5.I).build(),
                    Parameter.parameter("v1").values(Value5.V, Value5.IV, Value5.I, Value5.III, Value5.II).build(),
                    Parameter.parameter("x6").values(Config2.B, Config2.A).build()
            },
            new Parameter[] {
                    Parameter.parameter("x2").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x8").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x1").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v10").values(Value5.V, Value5.II, Value5.III, Value5.IV, Value5.I).build(),
                    Parameter.parameter("v7").values(Value5.V, Value5.I, Value5.IV, Value5.III, Value5.II).build(),
                    Parameter.parameter("x9").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v4").values(Value5.III, Value5.IV, Value5.II, Value5.V, Value5.I).build(),
                    Parameter.parameter("v2").values(Value5.V, Value5.I, Value5.II, Value5.IV, Value5.III).build(),
                    Parameter.parameter("v6").values(Value5.I, Value5.III, Value5.IV, Value5.II, Value5.V).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v5").values(Value5.III, Value5.V, Value5.IV, Value5.I, Value5.II).build(),
                    Parameter.parameter("v8").values(Value5.V, Value5.I, Value5.II, Value5.III, Value5.IV).build(),
                    Parameter.parameter("x6").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x10").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v9").values(Value5.I, Value5.V, Value5.II, Value5.III, Value5.IV).build(),
                    Parameter.parameter("x7").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v1").values(Value5.II, Value5.I, Value5.V, Value5.III, Value5.IV).build(),
                    Parameter.parameter("x4").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v3").values(Value5.V, Value5.IV, Value5.II, Value5.I, Value5.III).build()
            },
            new Parameter[] {
                    Parameter.parameter("x9").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v5").values(Value5.III, Value5.IV, Value5.II, Value5.I, Value5.V).build(),
                    Parameter.parameter("v4").values(Value5.III, Value5.V, Value5.II, Value5.IV, Value5.I).build(),
                    Parameter.parameter("x7").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v7").values(Value5.I, Value5.IV, Value5.V, Value5.III, Value5.II).build(),
                    Parameter.parameter("x2").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x3").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v6").values(Value5.I, Value5.V, Value5.III, Value5.II, Value5.IV).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v9").values(Value5.I, Value5.V, Value5.II, Value5.III, Value5.IV).build(),
                    Parameter.parameter("v10").values(Value5.V, Value5.IV, Value5.III, Value5.II, Value5.I).build(),
                    Parameter.parameter("x4").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v3").values(Value5.I, Value5.IV, Value5.II, Value5.V, Value5.III).build(),
                    Parameter.parameter("v2").values(Value5.IV, Value5.II, Value5.I, Value5.V, Value5.III).build(),
                    Parameter.parameter("x6").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x10").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v8").values(Value5.III, Value5.II, Value5.V, Value5.I, Value5.IV).build(),
                    Parameter.parameter("v1").values(Value5.II, Value5.III, Value5.I, Value5.V, Value5.IV).build(),
                    Parameter.parameter("x1").values(Config2.B, Config2.A).build()
            },
            new Parameter[] {
                    Parameter.parameter("v10").values(Value5.II, Value5.I, Value5.III, Value5.V, Value5.IV).build(),
                    Parameter.parameter("v5").values(Value5.I, Value5.V, Value5.II, Value5.IV, Value5.III).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x9").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x1").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v6").values(Value5.I, Value5.IV, Value5.V, Value5.III, Value5.II).build(),
                    Parameter.parameter("v3").values(Value5.II, Value5.IV, Value5.V, Value5.I, Value5.III).build(),
                    Parameter.parameter("x10").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v2").values(Value5.V, Value5.IV, Value5.I, Value5.II, Value5.III).build(),
                    Parameter.parameter("x6").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x4").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v8").values(Value5.I, Value5.V, Value5.II, Value5.IV, Value5.III).build(),
                    Parameter.parameter("x8").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v9").values(Value5.III, Value5.II, Value5.IV, Value5.V, Value5.I).build(),
                    Parameter.parameter("v1").values(Value5.II, Value5.III, Value5.I, Value5.V, Value5.IV).build(),
                    Parameter.parameter("x2").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x7").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v7").values(Value5.III, Value5.I, Value5.V, Value5.II, Value5.IV).build(),
                    Parameter.parameter("v4").values(Value5.III, Value5.I, Value5.IV, Value5.II, Value5.V).build()
            },
            new Parameter[] {
                    Parameter.parameter("x9").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x10").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v6").values(Value5.III, Value5.I, Value5.V, Value5.II, Value5.IV).build(),
                    Parameter.parameter("v10").values(Value5.IV, Value5.II, Value5.III, Value5.V, Value5.I).build(),
                    Parameter.parameter("v8").values(Value5.II, Value5.I, Value5.III, Value5.V, Value5.IV).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v5").values(Value5.IV, Value5.III, Value5.V, Value5.II, Value5.I).build(),
                    Parameter.parameter("v4").values(Value5.III, Value5.IV, Value5.V, Value5.II, Value5.I).build(),
                    Parameter.parameter("x7").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v2").values(Value5.III, Value5.V, Value5.I, Value5.II, Value5.IV).build(),
                    Parameter.parameter("v9").values(Value5.IV, Value5.II, Value5.I, Value5.III, Value5.V).build(),
                    Parameter.parameter("v7").values(Value5.I, Value5.III, Value5.IV, Value5.V, Value5.II).build(),
                    Parameter.parameter("x2").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v1").values(Value5.III, Value5.V, Value5.I, Value5.IV, Value5.II).build(),
                    Parameter.parameter("x1").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v3").values(Value5.III, Value5.I, Value5.IV, Value5.V, Value5.II).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x6").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x4").values(Config2.A, Config2.B).build()
            },
            new Parameter[]{
                    Parameter.parameter("x9").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x1").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v10").values(Value5.I, Value5.III, Value5.V, Value5.IV, Value5.II).build(),
                    Parameter.parameter("v9").values(Value5.I, Value5.V, Value5.II, Value5.IV, Value5.III).build(),
                    Parameter.parameter("v6").values(Value5.V, Value5.I, Value5.II, Value5.IV, Value5.III).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x10").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v4").values(Value5.IV, Value5.V, Value5.I, Value5.III, Value5.II).build(),
                    Parameter.parameter("v5").values(Value5.IV, Value5.I, Value5.V, Value5.III, Value5.II).build(),
                    Parameter.parameter("v3").values(Value5.V, Value5.IV, Value5.II, Value5.I, Value5.III).build(),
                    Parameter.parameter("v7").values(Value5.III, Value5.IV, Value5.V, Value5.II, Value5.I).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v1").values(Value5.V, Value5.II, Value5.IV, Value5.I, Value5.III).build(),
                    Parameter.parameter("x6").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x8").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x2").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x7").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v2").values(Value5.II, Value5.I, Value5.IV, Value5.III, Value5.V).build(),
                    Parameter.parameter("v8").values(Value5.IV, Value5.III, Value5.I, Value5.V, Value5.II).build(),
                    Parameter.parameter("x4").values(Config2.A, Config2.B).build()
            },
            new Parameter[] {
                    Parameter.parameter("x9").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x6").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v3").values(Value5.V, Value5.II, Value5.III, Value5.I, Value5.IV).build(),
                    Parameter.parameter("x1").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x7").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v4").values(Value5.IV, Value5.V, Value5.III, Value5.I, Value5.II).build(),
                    Parameter.parameter("v10").values(Value5.V, Value5.II, Value5.I, Value5.IV, Value5.III).build(),
                    Parameter.parameter("v6").values(Value5.III, Value5.IV, Value5.V, Value5.II, Value5.I).build(),
                    Parameter.parameter("x4").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x5").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x10").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x2").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v2").values(Value5.III, Value5.I, Value5.II, Value5.IV, Value5.V).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v5").values(Value5.II, Value5.I, Value5.V, Value5.IV, Value5.III).build(),
                    Parameter.parameter("v7").values(Value5.III, Value5.II, Value5.V, Value5.IV, Value5.I).build(),
                    Parameter.parameter("v1").values(Value5.III, Value5.IV, Value5.II, Value5.V, Value5.I).build(),
                    Parameter.parameter("v9").values(Value5.I, Value5.V, Value5.IV, Value5.III, Value5.II).build(),
                    Parameter.parameter("v8").values(Value5.IV, Value5.V, Value5.III, Value5.I, Value5.II).build()
            },
            new Parameter[] {
                    Parameter.parameter("v6").values(Value5.V, Value5.I, Value5.IV, Value5.III, Value5.II).build(),
                    Parameter.parameter("v4").values(Value5.III, Value5.I, Value5.V, Value5.II, Value5.IV).build(),
                    Parameter.parameter("x10").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x5").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v7").values(Value5.IV, Value5.I, Value5.III, Value5.II, Value5.V).build(),
                    Parameter.parameter("x1").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v2").values(Value5.I, Value5.III, Value5.II, Value5.IV, Value5.V).build(),
                    Parameter.parameter("x9").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("v10").values(Value5.V, Value5.III, Value5.IV, Value5.II, Value5.I).build(),
                    Parameter.parameter("v3").values(Value5.IV, Value5.III, Value5.I, Value5.II, Value5.V).build(),
                    Parameter.parameter("v9").values(Value5.III, Value5.IV, Value5.V, Value5.I, Value5.II).build(),
                    Parameter.parameter("x3").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v5").values(Value5.IV, Value5.V, Value5.III, Value5.I, Value5.II).build(),
                    Parameter.parameter("x4").values(Config2.B, Config2.A).build(),
                    Parameter.parameter("x2").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v8").values(Value5.II, Value5.IV, Value5.V, Value5.I, Value5.III).build(),
                    Parameter.parameter("x8").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x7").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("x6").values(Config2.A, Config2.B).build(),
                    Parameter.parameter("v1").values(Value5.II, Value5.I, Value5.V, Value5.IV, Value5.III).build()
            }
    };
}
